<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBwHH0Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBwHH0Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOBwHH0Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOBwHH0Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOBwHH0Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'OBwHH0Y',
    'container.build_id' => 'bcb1e205',
    'container.build_time' => 1606209672,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBwHH0Y');
